=== samirtenkoul/proyectosXML-DTD/E9_FormasGeometricas/E9_FormasGeometricas.dtd
<!ELEMENT formas (poligono+)>
<!ELEMENT poligono ((coordX,coordY)+ | nombre)>
<!ELEMENT coordX (#PCDATA)>
<!ELEMENT coordY (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>

=== samirtenkoul/proyectosXML-DTD/E9_FormasGeometricas/E9_FormasGeometricas.xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE formas SYSTEM "E9_FormasGeometricas.dtd">
<formas>
	<poligono>
		<coordX>12</coordX>
		<coordY>13</coordY>
		<coordX>17</coordX>
		<coordY>23</coordY>
		<coordX>34</coordX>
		<coordY>56</coordY>
	</poligono>
	<poligono>
		<nombre>Triángulo</nombre>
	</poligono>
	<poligono>
		<nombre>Rectángulo</nombre>
	</poligono>
</formas>
